In [1]:
from sklearn.datasets import make_classification

In [2]:
import torch

In [3]:
from torch.utils.data import Dataset, DataLoader

# Create Dataset

In [4]:
X , y = make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [5]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [6]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [7]:
x_tensor = torch.from_numpy(X)

In [8]:
y_tensor = torch.from_numpy(y)

In [9]:
y_tensor

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

# Dataset Class

In [10]:
class Customdataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):

    return self.features.shape[0]

  def __getitem__(self, index):

    return self.features[index], self.labels[index]

In [11]:
dataset = Customdataset(x_tensor, y_tensor)

In [12]:
dataset

In [13]:
len(dataset)

10

In [14]:
dataset[0]

(tensor([ 1.0683, -0.9701], dtype=torch.float64), tensor(1))

# DataLoader function

In [15]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [16]:
dataloader

In [17]:
for features, labels in dataloader:
  print(features)
  print(labels)
  print("-"*50)

tensor([[-0.5872, -1.9717],
        [ 1.7774,  1.5116]], dtype=torch.float64)
tensor([0, 1])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-2.8954,  1.9769]], dtype=torch.float64)
tensor([0, 0])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [ 1.0683, -0.9701]], dtype=torch.float64)
tensor([1, 1])
--------------------------------------------------
tensor([[-0.9382, -0.5430],
        [-1.1402, -0.8388]], dtype=torch.float64)
tensor([1, 0])
--------------------------------------------------
tensor([[-0.7206, -0.9606],
        [ 1.8997,  0.8344]], dtype=torch.float64)
tensor([0, 1])
--------------------------------------------------
