In [ ]:
import torch.nn as nn
import torch

## Create a Neural Network on Linear Model

In [ ]:
class MyNeuralNetwork(nn.Module):

  def __init__(self, num_params):
    super().__init__()
    self.linear = nn.Linear(in_features=num_params, out_features=1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, parameters):
    output = self.linear(parameters)
    output = self.sigmoid(output)

    return output

In [ ]:
features = torch.rand(10,5)

In [ ]:
features

tensor([[0.0547, 0.5561, 0.2038, 0.4447, 0.4757],
        [0.7761, 0.7818, 0.0039, 0.1662, 0.6692],
        [0.2827, 0.7715, 0.0741, 0.3624, 0.3367],
        [0.1700, 0.6435, 0.8501, 0.0942, 0.2508],
        [0.4136, 0.5081, 0.5481, 0.2276, 0.1118],
        [0.3761, 0.8107, 0.6786, 0.9920, 0.2078],
        [0.3956, 0.0136, 0.5600, 0.4706, 0.6468],
        [0.9289, 0.3759, 0.6097, 0.5428, 0.0433],
        [0.3738, 0.9901, 0.3244, 0.1880, 0.5371],
        [0.7377, 0.6331, 0.7634, 0.9738, 0.5127]])

In [ ]:
features.shape

torch.Size([10, 5])

In [ ]:
model = MyNeuralNetwork(num_params=features.shape[1])

In [ ]:
model(features)

tensor([[0.5586],
        [0.5343],
        [0.5671],
        [0.5716],
        [0.5524],
        [0.5406],
        [0.4956],
        [0.5046],
        [0.5713],
        [0.4973]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear.weight

Parameter containing:
tensor([[-0.2376,  0.2396, -0.0374, -0.1439, -0.1460]], requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([0.2564], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary

In [ ]:
summary(model=model, input_size=features.shape)

Layer (type:depth-idx)                   Output Shape              Param #
MyNeuralNetwork                          [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00